### ISSUE TITLE
Usage question with respect to tiles on the "edge" of an image"

### ISSUE THREAD

**Issue by sebi06** [buswinka/ryomen#1]
Hi,

I just testes this new cool package and have some questions.

* I load an image which has the size of 1024 x 1024
* the tile, apply a filer and show the image

Is there a way to avoid those black "egdes" after processing using you package?

![image](https://github.com/buswinka/ryomen/assets/3833249/99783c86-dac7-449c-ae65-b5b5ad91a761)

```python
import numpy as np
from ryomen import Slicer
from skimage.filters import median
from skimage.morphology import disk
from czitools import read_tools
import matplotlib.pyplot as plt
from tqdm import tqdm

filepath = r"F:\Testdata_Zeiss\CZI_Testfiles\nuc_AF568_1024x1024.czi"
array6d, mdata = read_tools.read_6darray(filepath)
img2d = array6d[0, 0, 0, 0, ...]
print(f"Shape of img2d: {img2d.shape}")

output: np.ndarray = np.empty(img2d.shape, dtype=np.dtype(np.uint16))
crop_size = (800, 800)
overlap = (64, 64)

slices = Slicer(
    img2d,
    crop_size=crop_size,
    overlap=overlap,
)

for crop, source, destination in tqdm(slices):
    crop = median(crop, footprint=disk(9))
    output[destination] = crop[source]

# show the results
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(12, 6))
ax[0].imshow(img2d, cmap="gray")
ax[1].imshow(output, cmap="gray")
plt.show()
```

**Comment by buswinka** [comment]
Thank you for bringing this into my attention -- It seems to be a bug with how padding is applied near the edges of images. A quick fix is to manually pad your image with np.pad() while I look into a fix.

**Comment by buswinka** [comment]
Hi @sebi06, This bug is fixed and I have pushed an update to pypi with version 0.0.4.

**Comment by sebi06** [comment]
Hi @buswinka 

I just updates the ryomen 0.0.5 and tested again but still get this artifact. Do I need to adapt my code?

![image](https://github.com/buswinka/ryomen/assets/3833249/41107105-7cda-4e24-a3cb-707265d52485)

**Comment by buswinka** [comment]
Yes sorry, please make the keyword argument `pad` to be true. 

```python
import numpy as np
from ryomen import Slicer
from skimage.filters import median
from skimage.morphology import disk
from czitools import read_tools
import matplotlib.pyplot as plt
from tqdm import tqdm

filepath = r"F:\Testdata_Zeiss\CZI_Testfiles\nuc_AF568_1024x1024.czi"
array6d, mdata = read_tools.read_6darray(filepath)
img2d = array6d[0, 0, 0, 0, ...]
print(f"Shape of img2d: {img2d.shape}")

output: np.ndarray = np.empty(img2d.shape, dtype=np.dtype(np.uint16))
crop_size = (800, 800)
overlap = (64, 64)

slices = Slicer(
    img2d,
    crop_size=crop_size,
    overlap=overlap,
    pad=True,  # <------- Set this to True to pad with reflections. 
)

for crop, source, destination in tqdm(slices):
    crop = median(crop, footprint=disk(9))
    output[destination] = crop[source]

# show the results
fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(12, 6))
ax[0].imshow(img2d, cmap="gray")
ax[1].imshow(output, cmap="gray")
plt.show()
```

**Comment by buswinka** [comment]
Hi @sebi06, I am re-opening this issue as I found additional bugs which I am now fixing. Please hold off until then!

**Comment by buswinka** [comment]
Should be fixed now in version 0.0.6 -- padding is now applied by default.
